### ISSUE TITLE
Статистика по пользователям 

### ISSUE THREAD

**Issue by Aldikeeva** [qlt2020/doskaz#10]
https://doskaz.kz/adminpanel/statisticks/user

- [x] настроить экспорт при фильтрации 
Сейчас фильтрация не применяется в документе экспорта

- [x] Закрепить строки при скролле 
![image](https://user-images.githubusercontent.com/70937147/133976164-978a27b1-5737-449b-b24f-821048421c25.png)

- [x] Сортировать города как на карте: Весь РК, ГОБ, ГРЗ и остальные города
![image](https://user-images.githubusercontent.com/70937147/133976233-ef449afb-d676-4372-86ad-dede62bcec66.png)

- [x] Присвоить всем существующим пользователям в ЛК пол "Не выбран" - сейчас в статистике значение не учитывается и поля выводятся как 0
![image](https://user-images.githubusercontent.com/70937147/133976446-ba144c40-403e-4ab2-a53a-5e1bf346e5fa.png)

**Comment by Kainar9292** [comment]
#plan 300

**Comment by Kainar9292** [comment]
#fact120

**Comment by AkbayK** [comment]
#plan 120

**Comment by AkbayK** [comment]
#fact 90

**Comment by Aldikeeva** [comment]
Правки на фронт: 
Убрать категорию "Просто просмотреть" - из таблицы и селекта 
это не группа маломобильности))) 
![image](https://user-images.githubusercontent.com/70937147/134475166-a935717e-d0fa-48eb-a373-89517cea03b8.png)
