### ISSUE TITLE
Вывести общую статистику на внешку 

### ISSUE THREAD

**Issue by Aldikeeva** [qlt2020/doskaz#116]
### Описание 

Приступить к задаче после всех правок по статистике

1. Нужно вывести общую статистику на внешку:
![image](https://user-images.githubusercontent.com/70937147/135440025-1022f2e5-0ea5-432b-87bf-532fc12f4d6f.png)

Общая статистика - https://doskaz.kz/adminpanel/statisticks/statisticks
![image](https://user-images.githubusercontent.com/70937147/135439796-e12efce4-a8a0-41f9-85fe-557e6cd0574a.png)

**Comment by Kainar9292** [comment]
#plan 480
