### ISSUE TITLE
Поправить экспорт Общей статистики 

### ISSUE THREAD

**Issue by Aldikeeva** [qlt2020/doskaz#144]
[7.10.2021_Статистика (1).pdf](https://github.com/qlt2020/doskaz/files/7301674/7.10.2021_.1.pdf)
![image](https://user-images.githubusercontent.com/70937147/136365588-51c36ead-4da1-4bdd-a936-a1b3b729bd59.png)
![image](https://user-images.githubusercontent.com/70937147/136365748-3362b689-b938-4c50-902f-f0a2ff2501eb.png)

**Comment by Kainar9292** [comment]
#plan 80
