### ISSUE TITLE
Поиск объектов на карте 

### ISSUE THREAD

**Issue by Aldikeeva** [qlt2020/doskaz#146]
1. Если выбран изначально город Павлодар и в поиске указать наименование объекта или адрес, то при смене города на Актобе результаты поиска будут города Павлодар:
![Безымянный](https://user-images.githubusercontent.com/70937147/136526893-106bc1a1-bfbb-4abd-92f6-63b68d0a0644.png)
 
сбрасывать поиск при смене города 

2. Убрать поиск по нажатию на кнопку Enter, только выбор в списке

3. Можно еще перепроверить почему не ищет по адресу Торайгырова 44/1 (г.Павлодар)
![image](https://user-images.githubusercontent.com/70937147/136529079-e4f12d07-0024-4247-9b4c-bb3e1e74c0c8.png)

4. Добавить скролл, чтобы можно было просмотреть все результаты 
![image](https://user-images.githubusercontent.com/70937147/136756695-64f1caea-4872-4c9e-950e-103c6f99b182.png)

**Comment by Kainar9292** [comment]
#plan 120
