### ISSUE TITLE
Панель меню. Карта 

### ISSUE THREAD

**Issue by Aldikeeva** [qlt2020/doskaz#155]
При смене языка на Английский и Казахский пропадает выбор города и выбор категории маломобильности в меню:
![image](https://user-images.githubusercontent.com/70937147/136933536-67f3f367-bff3-471a-9666-5fe7f923bae5.png)
__________________
**Мы убрали на других страницах, кроме карты, выбор города и категории, чтобы фильтрация не применялась. Возможно из-за этого и при смене языка данные элементы пропадают**

- [x] При смене языка на карте выводить элементы в меню: Выбор города и выбор Категории маломобильности
!На остальных страницах данные элементы в меню не выводить.
![image](https://user-images.githubusercontent.com/70937147/136933481-69d2f9f6-e961-44d5-acde-27e7f46bac98.png)

**Comment by Kainar9292** [comment]
#plan 60
