### ISSUE TITLE
Добавить перевод для английской и казахской версии

### ISSUE THREAD

**Issue by Aldikeeva** [qlt2020/doskaz#163]
Соглашения о неразглашении - Non-disclosure agreements - Жарияламау туралы келісімдер
![image](https://user-images.githubusercontent.com/70937147/137072445-d1435ba7-b06d-47cf-99d8-db3189391f22.png)

**Comment by Kainar9292** [comment]
#plan 30

**Comment by Kainar9292** [comment]
#fact 5
