### ISSUE TITLE
Добавить лоадер на страницы статистики 

### ISSUE THREAD

**Issue by Aldikeeva** [qlt2020/doskaz#165]
- Добавить лоадер на страницы статистики 
- Футер закрепить снизу(чтобы при загрузке не поднимался на середину страницы): 
![image](https://user-images.githubusercontent.com/70937147/137075074-824f2327-051a-471b-9fdd-df8233cb1de7.png)

Лоадер можно примерно такой: 
![image](https://user-images.githubusercontent.com/70937147/137075220-b94056a2-c97d-4ad4-bfec-e10ea82c166d.png)

**Comment by Kainar9292** [comment]
#fact 50
