### ISSUE TITLE
Залить переводы на бэк

### ISSUE THREAD

**Issue by Aldikeeva** [qlt2020/doskaz#18]
**отправила в дискорде два файла(сюда формат не загружается)** 
параметры оценки доступности - файл attributes.kz.yaml
категории/подкатегории - файл Категория - Подкатегория ГОТОВО.txt

**Comment by dosarkz** [comment]
done 
#fact 8

**Comment by Aldikeeva** [comment]
Не перевелись: 
<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

(до 18.02.2019 г.) при высоте подъёма выше 20 см — 1 : 20 (5% или 2,9°)  При высоте подъёма до 20 см — 1 : 10 (10% или 5,7°) | "(до 18.02.2019 г.) при высоте подъёма выше 20 см — 1 : 20 (5% или 2,9°) \\n При высоте подъёма до 20 см — 1 : 10 (10% или 5,7°)": "(before 18.02.2019) At a lifting height above 20 cm - 1:20 (5% or 2.9°). \\n At a lifting height up to 20 cm - 1:10 (10% or 5.7°)"
-- | --
(после 18.02.2019 г.) при высоте подъёма выше 20 см — 1 : 12 (8% или 4,8°)  При высоте подъёма до 20 см — 1 : 10 (10% или 5,7°) | "(после 18.02.2019 г.) при высоте подъёма выше 20 см — 1 : 12 (8% или 4,8°) \\nПри высоте подъёма до 20 см — 1 : 10 (10% или 5,7°)"": ""(after 18.02.2019) With a lift height above 20 cm - 1:12 (8% or 4.8°) \\nWith a lift height up to 20 cm - 1:10 (10% or 5.7°)"
Детский стульчик: наличие стульчика с пятиточечным ремнем либо ограничителем между ног | "Детский стульчик: наличие стульчика с пятиточечным ремнем либо ограничителем между ног": "Highchair: availability of a highchair with a five-point belt or a restraint between the legs"
Рельефные тактильные обозначения путей движения: | "Рельефные тактильные обозначения путей движения: "Embossed tactile markers of paths of motion"
<google-sheets-html-origin><style type="text/css"></style>

Универсальная кабина – не менее 1,65 х 2,0 м | "Универсальная кабина – не менее 1,65 х 2,0 м": "Universal toilet cubicle - not less than 1.65x2.0 m"
-- | --



</body>
</html>


не перевелся текст(я изменила на русском текст "криптограмма" на "пиктограмма", скорее всего из-за этого):
<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

Снаружи размещена криптограмма | "Снаружи размещена пиктограмма": "Tactile pictograms placed outside"
-- | --



</body>
</html>


не было перевода:
<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

Не менее 0,9 м х 1,5 м | "Free space in front - not less than 0.9x1.5 m"
-- | --
Не менее 0,9 х 1,2 м | Параметры не менее 0,9 х 1,2 м: "Parameters not less than 0.9 x 1.2 m"
Легкость открытия и закрытия двери (усилие открывания не более 50 Нм) | "Легкость открытия и закрытия двери (усилие открывания не более 50Нм)": "Easiness of opening and closing the door (force for opening no more than 50 N·m)"


</body>
</html>

**Comment by dosarkz** [comment]
donw
