### ISSUE TITLE
Вывести статистику по доступности объектов на внешку

### ISSUE THREAD

**Issue by Aldikeeva** [qlt2020/doskaz#19]
Приступить к задаче после завершения https://github.com/qlt2020/doskaz/issues/2

- [x] Вывести на карту кнопку "Просмотреть статистику"
диз: https://www.figma.com/file/hBRqAQFl2AXMSLk9cm3z8M/ДосКаз?node-id=1%3A2
![image](https://user-images.githubusercontent.com/70937147/133984099-3d60a45c-e65c-4456-98ce-726ed3c07b4d.png)

адаптив: https://www.figma.com/file/xS8c7heoKEjsETlYX8nF4S/doskaz-adaptive?node-id=11%3A2302
![image](https://user-images.githubusercontent.com/70937147/133984144-8152e1d1-12e8-4f52-ab91-4f48f08baa78.png)

- [x] Разместить статистику на странице: 
![image](https://user-images.githubusercontent.com/70937147/133984386-b8b32bf2-86ea-4608-b29d-fe9750376a64.png)

как на адаптиве можно реализовать? все не вместится (напишите мне по данному вопросу)

**Comment by Kainar9292** [comment]
#400
