### ISSUE TITLE
Статистика по доступности объектов

### ISSUE THREAD

**Issue by Aldikeeva** [qlt2020/doskaz#2]
### Описание

- [x] 1. Настроить экспорт статистики при фильтрации 
Сейчас фильтрация не применяется в документе экспорта

- [x] 2. Добавить параметры фильтрации
- Категория маломобильных групп населения
- Статус доступности: Доступно, Не доступно, Частично доступно

3. По полям
- [x] Убрать поля Общее и "Для всех групп"
- [x] Добавить поле Общее в каждую группу маломобильности
![image](https://user-images.githubusercontent.com/70937147/133963580-7d21e97b-3072-472c-9eaf-9f78954580d6.png)

4.  В таблице выделить жирным шрифтом категории объектов, например «Образование», «Здравоохранение», «Торговля и услуги» и т.д. 
Нужно сделать еще жирнее и всю строку 
![image](https://user-images.githubusercontent.com/70937147/133964689-ffed909b-9e89-4e1f-85d7-dd6b3899dcf5.png)

5. Закрепить поля при скролле
![image](https://user-images.githubusercontent.com/70937147/133976589-7eb10188-916b-4c79-ac77-6306aac515a3.png)

**Comment by Kainar9292** [comment]
#plan 400

**Comment by Kainar9292** [comment]
#fact 450

**Comment by AkbayK** [comment]
#plan 480

**Comment by AkbayK** [comment]
$fact 780
