### ISSUE TITLE
Для раздела Помощь и Медиатека добавить изображение для языковых версия 

### ISSUE THREAD

**Issue by Aldikeeva** [qlt2020/doskaz#235]
- [x] 1. Помощь - https://doskaz.kz/adminpanel/help/posts/create
![image](https://user-images.githubusercontent.com/70937147/139621438-d3a43ed4-ac93-46da-94da-66ef1c099fa4.png)

- Изображение для русской версии 
- Изображение для казахской версии 
- Изображение для английской версии 

(создание и редактирование записи в разделе Помощь) 

- [x] 2. Медиатека - https://doskaz.kz/adminpanel/blog/posts
![image](https://user-images.githubusercontent.com/70937147/139621549-c8762c36-3666-428f-a8f3-f4c3952a051f.png)

- Изображение для русской версии 
- Изображение для казахской версии 
- Изображение для английской версии 

(создание и редактирование материала в разделе Медиатека)

**Comment by alisherin** [comment]
#plan 480

**Comment by alisherin** [comment]
#fact 180
