### ISSUE TITLE
Подключить поля Изображения(в языковых версиях) в админке и на внешке

### ISSUE THREAD

**Issue by Aldikeeva** [qlt2020/doskaz#237]
Задача на бэке - https://github.com/qlt2020/doskaz/issues/235

**Подключить api в админке** 

1. Помощь - https://doskaz.kz/adminpanel/help/posts/create
2. Медиатека - https://doskaz.kz/adminpanel/blog/posts

- Изображение для русской версии
- Изображение для казахской версии
- Изображение для английской версии
(создание и редактирование записи в разделе Помощь)

**Comment by Kainar9292** [comment]
#plan 60
