### ISSUE TITLE
У пользователя Администратор не работает перевод Помощи

### ISSUE THREAD

**Issue by Aldikeeva** [qlt2020/doskaz#245]
Если пользователь с ролью Администратор авторизован в системе - переводы не работают в разделе "Помощь": 
![image](https://user-images.githubusercontent.com/70937147/139798903-a580c47a-7ce7-418f-9904-976ee853d2fa.png)

**Comment by alisherin** [comment]
#plan 120

**Comment by alisherin** [comment]
#fact 120
