### ISSUE TITLE
Текст обязательного заполнения поля на адаптиве 

### ISSUE THREAD

**Issue by Aldikeeva** [qlt2020/doskaz#28]
### Описание 

Заполнения обратной связи на адаптиве - если неправильно заполнить поле Эл.почта выводится текст "Значение адреса электронной почты недопустимо." - на страницах адаптива текст не вмещается, вывести его в две строки:
https://doskaz.qlt.kz/contacts
![image](https://user-images.githubusercontent.com/70937147/133757897-59dd9870-2967-4c2d-83bc-cdd464db19f6.png)

**Comment by dzaybatsu** [comment]
#plan 20
