### ISSUE TITLE
При редактировании материала в разделе Помощь выходит ошибка

### ISSUE THREAD

**Issue by Aldikeeva** [qlt2020/doskaz#30]
При редактировании материала в разделе Помощь выходит ошибка:

```
{message: "No route found for "PUT /api/help/3": Method Not Allowed (Allow: GET, POST, DELETE)",…}
code: 405
message: "No route found for \"PUT /api/help/3\": Method Not Allowed (Allow: GET, POST, DELETE)"
```

https://doskaz.kz/adminpanel/help/posts/3
![image](https://user-images.githubusercontent.com/70937147/133998877-13ef788c-4110-42ad-97fc-6f48ff9d1b34.png)

**Comment by alisherin** [comment]
#plan 60

**Comment by Aldikeeva** [comment]
При редактировании материала помощи также выходит ошибка: _**405 Request failed with status code 405**_

 
> {"message":"No route found for \"PUT \/api\/help\/4\": Method Not Allowed (Allow: GET, POST, DELETE)","code":405}


![image](https://user-images.githubusercontent.com/70937147/134628669-e76e7183-3d90-428e-98b0-3a62378feb75.png)
