### ISSUE TITLE
При сортировке материалов медиатеки за период выводятся удаленные материалы

### ISSUE THREAD

**Issue by Aldikeeva** [qlt2020/doskaz#31]
При сортировке материалов медиатеки за период выводятся удаленные материалы в админке:
https://doskaz.kz/blog?post_date_from=2020-01-01&post_date_to=2021-09-20
![image](https://user-images.githubusercontent.com/70937147/133999333-f66481a7-ff8f-4d5c-8fbb-6b671b468807.png)

при открытии материала выходит ошибка: 
https://doskaz.kz/blog/obyavleniya/kontent-skoro-budet-dostupen
![image](https://user-images.githubusercontent.com/70937147/133999363-693de443-dff3-4112-b48c-414bde5c7c0e.png)

**Comment by AkbayK** [comment]
#fact 20
