### ISSUE TITLE
Если объект или новость в медиатеке были удалены - удалять его в ЛК пользователя

### ISSUE THREAD

**Issue by Aldikeeva** [qlt2020/doskaz#34]
Если объект или новость в медиатеке были удалены - не отправлять на фронт в ЛК пользователя во вкладке Комментарии
https://doskaz.kz/profile/comments
![image](https://user-images.githubusercontent.com/70937147/134002804-c9b3f4a5-7443-4c3f-bc5b-2e63383c8c64.png)

**Comment by alisherin** [comment]
#plan 60
