### ISSUE TITLE
ЛК пользователя - Уведомления 

### ISSUE THREAD

**Issue by Aldikeeva** [qlt2020/doskaz#37]
Если объект был добавлен, а после удален - в лк Пользователя (вкладка Уведомления) удалять запись:
https://doskaz.kz/profile/notifications
![image](https://user-images.githubusercontent.com/70937147/134003394-2593097b-ba8b-406c-bc88-a45bab3e04c4.png)

т.к. по ссылке он уже становится не доступен: https://doskaz.kz/objects/179759
![image](https://user-images.githubusercontent.com/70937147/134003446-036b47d5-9b98-4735-b7bf-511cdd1481c4.png)

**Comment by alisherin** [comment]
#plan 60
