### ISSUE TITLE
Страница Помощь - Просмотр помощи

### ISSUE THREAD

**Issue by Aldikeeva** [qlt2020/doskaz#40]
Шапку сделать в таком виде: 
![image](https://user-images.githubusercontent.com/70937147/134005733-69fd6192-c970-45ba-97e0-3b133345300b.png)
Ниже разделы в таком виде: Карта - Помощь - О карте - Медиатека - Контакты 
![image](https://user-images.githubusercontent.com/70937147/134005765-83da1df0-ae79-49d0-9fe2-2b6547339d25.png)

- [ ] Установить изменение шрифта для текста  (размер шрифтов сделать как на главной странице):
заголовки
![image](https://user-images.githubusercontent.com/70937147/134006673-1d411d5e-762c-440c-8155-e841c7db3150.png)

- [ ] Настроить цветовую схему: 
![image](https://user-images.githubusercontent.com/70937147/134008202-40afe470-1c64-4045-8743-e385e4fbdb90.png)

- [ ] На главной странице (Карте) https://doskaz.kz/ прописать ссылку на страницу Помощь:
![image](https://user-images.githubusercontent.com/70937147/134006493-d12bd45e-9ff5-47c9-9394-0c81af863c1a.png)

**Comment by amanum** [comment]
#plan 180
