### ISSUE TITLE
Страница О карте 

### ISSUE THREAD

**Issue by Aldikeeva** [qlt2020/doskaz#41]
Шапку сделать в таком виде:
![image](https://user-images.githubusercontent.com/70937147/134005733-69fd6192-c970-45ba-97e0-3b133345300b.png)
Ниже разделы в таком виде: Карта - Помощь - О карте - Медиатека - Контакты 
![image](https://user-images.githubusercontent.com/70937147/134005765-83da1df0-ae79-49d0-9fe2-2b6547339d25.png)

- [ ] Установить изменение шрифта для текста (размер шрифтов сделать как на главной странице):
![image](https://user-images.githubusercontent.com/70937147/134008341-17d0f202-69e1-40c4-bf09-dacaec0513d0.png)

- [ ] Настроить цветовую схему:
![image](https://user-images.githubusercontent.com/70937147/134008452-afaa5739-d065-4495-8bef-19637a61925e.png)

- [ ] Ссылки сделать жирнее перекрасить в черный цвет или белый цвет в зависимости от цветовой схемы
![image](https://user-images.githubusercontent.com/70937147/134008948-1cc03699-2d94-4767-9d50-6bfc5db0fc41.png)

- [ ] Активную вкладку тоже перекрасить в черный цвет или белый цвет в зависимости от цветовой схемы и сделать жирнее

**Comment by amanum** [comment]
#plan 180
