### ISSUE TITLE
Страница Медиатека - Просмотр материала

### ISSUE THREAD

**Issue by Aldikeeva** [qlt2020/doskaz#42]
Шапку сделать в таком виде: 
![image](https://user-images.githubusercontent.com/70937147/134005733-69fd6192-c970-45ba-97e0-3b133345300b.png)
Ниже разделы в таком виде: Карта - Помощь - О карте - Медиатека - Контакты 
![image](https://user-images.githubusercontent.com/70937147/134005765-83da1df0-ae79-49d0-9fe2-2b6547339d25.png)

- [ ] Установить изменение шрифта для текста при просмотре списка и просмотре материалов медиатеки (размер шрифтов сделать как на главной странице):
![image](https://user-images.githubusercontent.com/70937147/134009246-f9e7d62b-eec5-41ad-bdb4-48b4df8af061.png)
при просмотре материала тоже: 
![image](https://user-images.githubusercontent.com/70937147/134009347-38d4946b-7f4f-453d-bfde-bd89a5e00463.png)

- [ ] Настроить цветовую схему: 
![image](https://user-images.githubusercontent.com/70937147/134009310-3be3a322-f31e-41b6-b9a7-38083acba721.png)
при просмотре материала тоже: 
![image](https://user-images.githubusercontent.com/70937147/134009353-be4f9008-7f7d-47f9-920b-1109138ea63c.png)

**Comment by amanum** [comment]
#plan 240

**Comment by amanum** [comment]
#fact 300
