### ISSUE TITLE
Подать жалобу

### ISSUE THREAD

**Issue by Aldikeeva** [qlt2020/doskaz#43]
**Шапку сделать в таком виде:** 
![image](https://user-images.githubusercontent.com/70937147/134005733-69fd6192-c970-45ba-97e0-3b133345300b.png)

**Ниже разделы в таком виде: Карта - Помощь - О карте - Медиатека - Контакты** 
![image](https://user-images.githubusercontent.com/70937147/134005765-83da1df0-ae79-49d0-9fe2-2b6547339d25.png)

- [ ] Установить изменение шрифта для текста при просмотре списка и просмотре материалов медиатеки (размер шрифтов сделать как на главной странице):
- [ ] Настроить цветовую схему: 
![image](https://user-images.githubusercontent.com/70937147/134116004-71bff03e-bcab-429e-a42a-91a7ccbf8467.png)

- [ ] Все цветные элементы перекрасить в черный или белый в зависимости от цветовой схемы (кроме картинок)
![image](https://user-images.githubusercontent.com/70937147/134116019-00014f57-526f-442c-8797-c608d45d0b77.png)

**Comment by amanum** [comment]
#plan 180

**Comment by amanum** [comment]
#plan 30
