### ISSUE TITLE
Добавить объект

### ISSUE THREAD

**Issue by Aldikeeva** [qlt2020/doskaz#44]
**Шапку сделать в таком виде:** 
![image](https://user-images.githubusercontent.com/70937147/134005733-69fd6192-c970-45ba-97e0-3b133345300b.png)

**Ниже разделы в таком виде: Карта - Помощь - О карте - Медиатека - Контакты** 
![image](https://user-images.githubusercontent.com/70937147/134005765-83da1df0-ae79-49d0-9fe2-2b6547339d25.png)

- [x] Установить изменение шрифта для текста при просмотре списка и просмотре материалов медиатеки (размер шрифтов сделать как на главной странице):
- [x] Настроить цветовую схему: 
![image](https://user-images.githubusercontent.com/70937147/134115546-a7af7651-0f18-4bdf-b3a9-0ee8c9f580dd.png)

- [ ] Оценка зоны не выводится - нужно сделать ее тоже черной или белой в зависимости от цветовой схемы и 
![image](https://user-images.githubusercontent.com/70937147/134115608-b15d3d7b-7dfc-4b03-b1a1-967bb6441bc2.png)
![image](https://user-images.githubusercontent.com/70937147/134115654-04e3950e-4b53-470d-a20c-18180811171e.png)

- [x] Все цветные элементы перекрасить в черный или белый в зависимости от цветовой схемы (кроме картинок)
![image](https://user-images.githubusercontent.com/70937147/134115702-c29e8941-0d51-4d79-80a0-5ac0b82fac3a.png)

**Применить для:** 

- Базовая форма
- Форма для волонтеров
- Форма для экспертов

**Comment by amanum** [comment]
#fact 120

**Comment by Aldikeeva** [comment]
Оценка доступности зоны не выводится: 
![image](https://user-images.githubusercontent.com/70937147/134628396-a5ae8768-9e29-4d2b-8d34-b013a78f7391.png)
Нужно выводить так, только черно белым цветом: 
![image](https://user-images.githubusercontent.com/70937147/134628449-a4e3f78c-a46e-47fe-9cf2-cdb52d45f6a1.png)
