### ISSUE TITLE
Страница 404

### ISSUE THREAD

**Issue by Aldikeeva** [qlt2020/doskaz#46]
**Шапку сделать в таком виде:** 
![image](https://user-images.githubusercontent.com/70937147/134005733-69fd6192-c970-45ba-97e0-3b133345300b.png)

**Ниже разделы в таком виде: Карта - Помощь - О карте - Медиатека - Контакты** 
![image](https://user-images.githubusercontent.com/70937147/134005765-83da1df0-ae79-49d0-9fe2-2b6547339d25.png)

- [ ] Установить изменение шрифта для текста при просмотре списка и просмотре материалов медиатеки (размер шрифтов сделать как на главной странице):
- [x] Настроить цветовую схему

- [x] Сделать фон черно-белым

сейчас у этой страницы  нет версии для слабовидящих: 
![image](https://user-images.githubusercontent.com/70937147/134116096-12a33921-7b6a-4eb1-83a2-c6721954780d.png)

**Comment by amanum** [comment]
#plan 120
