### ISSUE TITLE
Страница Контакты

### ISSUE THREAD

**Issue by Aldikeeva** [qlt2020/doskaz#47]
Шапку сделать в таком виде: 
![image](https://user-images.githubusercontent.com/70937147/134005733-69fd6192-c970-45ba-97e0-3b133345300b.png)

Ниже разделы в таком виде: Карта - Помощь - О карте - Медиатека - Контакты 
![image](https://user-images.githubusercontent.com/70937147/134005765-83da1df0-ae79-49d0-9fe2-2b6547339d25.png)

- [ ] Установить изменение шрифта для текста при просмотре списка и просмотре материалов помощи (размер шрифтов сделать как на главной странице):
- [ ] Настроить цветовую схему: 
![image](https://user-images.githubusercontent.com/70937147/134115313-7638b290-0227-4747-b093-3d506179bb8e.png)

- [ ] Все цветные элементы перекрасить в черный или белый в зависимости от цветовой схемы (кроме картинок)
![image](https://user-images.githubusercontent.com/70937147/134115334-3a230b62-4ef5-49c0-9076-2737f93c0916.png)
![image](https://user-images.githubusercontent.com/70937147/134115367-047b36c7-8ca3-4c45-90c0-c3af73d17fee.png)

**Comment by amanum** [comment]
#plan 120

**Comment by amanum** [comment]
#fact 120
