### ISSUE TITLE
Страницы ЛК

### ISSUE THREAD

**Issue by Aldikeeva** [qlt2020/doskaz#48]
Шапку сделать в таком виде: 
![image](https://user-images.githubusercontent.com/70937147/134005733-69fd6192-c970-45ba-97e0-3b133345300b.png)
Ниже разделы в таком виде: Карта - Помощь - О карте - Медиатека - Контакты 
![image](https://user-images.githubusercontent.com/70937147/134005765-83da1df0-ae79-49d0-9fe2-2b6547339d25.png)

- [x] Установить изменение шрифта для текста при просмотре списка и просмотре материалов помощи (размер шрифтов сделать как на главной странице):
- [x] Настроить цветовую схему: 
![image](https://user-images.githubusercontent.com/70937147/134114546-89843c57-8180-4bd3-a149-5c87ba752fac.png)

- [x] Все цветные элементы перекрасить в черный или белый в зависимости от цветовой схемы (кроме картинок)
![image](https://user-images.githubusercontent.com/70937147/134115034-64668ffc-1013-4aa1-b4a3-82493515a2a8.png)

- [x] Применить изменения для всех вкладок (Достижения, Объекты, Жалобы и т.д.)  и перепроверить отображение всех элементов
![image](https://user-images.githubusercontent.com/70937147/134115228-036a4ae7-f7a7-458b-a5b0-6be66d6b5259.png)

**Comment by amanum** [comment]
#plan 120

**Comment by amanum** [comment]
#fact 360

**Comment by Aldikeeva** [comment]
1. Убрать границу (линию) в двух цветовых схемах:
![image](https://user-images.githubusercontent.com/70937147/134627911-aab7665a-5556-4b34-b9b7-edbde0118416.png)
![image](https://user-images.githubusercontent.com/70937147/134627966-031dba8f-5e8c-4322-a399-1125197cddad.png)


2. В черной цветовой схеме поля окрашены в белый: 
Мои задания 
![image](https://user-images.githubusercontent.com/70937147/134628076-828882cd-1ac1-4598-a8f2-300c2c382312.png)
Мои комментарии
![image](https://user-images.githubusercontent.com/70937147/134628085-4a6f9e13-c4ee-42eb-97e6-aa8f7f13785d.png)
