### ISSUE TITLE
Модерация комментариев 

### ISSUE THREAD

**Issue by Aldikeeva** [qlt2020/doskaz#5]
### Отзывы на объект 

- [ ] После добавления отзыва - убрать автоматическую публикацию 
- [ ] Добавить в админку раздел Отзывы 

Схема работы: 
1. Пользователь оставляет отзыв
2. В админке появляется запись в таблице
3. Администратор модерирует отзыв
4. У пользователя в ЛК отзыв выводится только после публикации 

**Поля в таблице:** 
Наименование объекта (ссылка, по нажатию на наименование объекта открывается страница просмотра в админке) 
Пользователь 
Текст отзыва
Кнопки "Принять" и "Отклонить"
- По нажатию на кнопку "Принять" отзыв публикуется
- По нажатию на кнопку "Отклонить" отзыв не публикуется (если был опубликован становится не опубликованным - пропадет на сайте) 

________

### Комментарии в медиатеке

- [x] После добавления комментария - убрать автоматическую публикацию 
- [x] Добавить в админку раздел Комментарии

Схема работы: 
1. Пользователь оставляет комментарий 
2. В админке появляется запись в таблице
3. Администратор модерирует комментарий 
4. У пользователя в ЛК комментарий выводится только после публикации 

**Поля в таблице:** 
Наименование материала(материала медиатеки) - ссылка, по нажатию на наименование материала открывается страница просмотра в админке)   
Пользователь 
Текст комментария
Кнопки "Принять" и "Отклонить"
- По нажатию на кнопку "Принять" комментарий публикуется
- По нажатию на кнопку "Отклонить" комментарий не публикуется (если был опубликован становится не опубликованным - пропадет на сайте)

**Comment by Balkenov** [comment]
#plan 960

**Comment by Aldikeeva** [comment]
- Если комментарий/отзыв в админке еще не опубликован, не выводить у пользователя в ЛК
- Если комментарий/отзыв был отклонен, убирать его в ЛК у пользователя
