### ISSUE TITLE
Версия для слабовидящих - модалки

### ISSUE THREAD

**Issue by Aldikeeva** [qlt2020/doskaz#51]
НЕ выводятся модальные окна: 
- После добавления объекта 
- После подачи жалобы

ИЗМЕНИТЬ модальные окна: 
- При первой авторизации "Относитесь к маломобильным группам населения"
- "Подписка на уведомления"
- "Вы подписались на уведомления"
- "Вы сменили категорию, хотите подписаться на уведомления"
- "Отписка от уведомлений"
и т.д.
![image](https://user-images.githubusercontent.com/70937147/134118098-19f67cab-fb2c-48b3-9ea2-db2c2e86629c.png)
![image](https://user-images.githubusercontent.com/70937147/134118105-fbc25330-1d77-4a07-ab96-fe0f4ea05658.png)

Все модалки должны выглядеть так в зависимости от версии цветовой схемы и шрифта:
![image](https://user-images.githubusercontent.com/70937147/134118421-4d834e92-4453-4518-95c8-135ae5e2fb5e.png)

**Comment by amanum** [comment]
#plan 60

**Comment by amanum** [comment]
#fact 0
