### ISSUE TITLE
При пердпросмотре и просмотре объекта убрать панель меню

### ISSUE THREAD

**Issue by Aldikeeva** [qlt2020/doskaz#53]
При пердпросмотре и просмотре объекта убрать панель меню

![image](https://user-images.githubusercontent.com/70937147/134119984-5efd1639-c5c3-4f98-aa5d-695e28482507.png)
![image](https://user-images.githubusercontent.com/70937147/134120000-36900192-775a-48ec-a516-5f4268c8e8ab.png)

**Comment by Rokatoka** [comment]
#plan 30
