### ISSUE TITLE
При нажатии на кнопку "Подать жалобу" выводится ошибка

### ISSUE THREAD

**Issue by Aldikeeva** [qlt2020/doskaz#54]
Что привело к ошибке: 
1. В системе не авторизовалась
2. Нажала на кнопку Подать жалобу
3. Вышло окно авторизации - я закрыла его 
4. Снова нажала на кнопку Подать жалобу 
5. Открылась страница с ошибкой: 
![image](https://user-images.githubusercontent.com/70937147/134120200-b3975e36-ddf6-4e5d-8411-7130199a6c37.png)

**Эта же ошибка на веб версии** 

У Кайрата с первого раза по нажатию на кнопку Подать жалобу (пользователь не был авторизован) сразу вышла ошибка. Нужно перепроверить

**Comment by Rokatoka** [comment]
#plan 60

**Comment by Rokatoka** [comment]
#fact 60
