### ISSUE TITLE
Mozilla - ЛК пользователя

### ISSUE THREAD

**Issue by Aldikeeva** [qlt2020/doskaz#62]
В лк скролл отличается: 
в первом случае он не нужен
во втором случае - он отличается от диза: 
![image](https://user-images.githubusercontent.com/70937147/134122110-39cf78b9-f491-489f-a51e-d62043162433.png)
![image](https://user-images.githubusercontent.com/70937147/134122121-13c22cc6-577e-450d-a07e-87025bd859a5.png)

**Comment by dzaybatsu** [comment]
#plan 30

**Comment by dzaybatsu** [comment]
#plan 25
