### ISSUE TITLE
Валидация на фото при Подаче жалобы

### ISSUE THREAD

**Issue by Aldikeeva** [qlt2020/doskaz#64]
установить валидацию на фото при Подаче жалобы 
![image](https://user-images.githubusercontent.com/70937147/134123302-eaaeb980-1e29-4072-84d4-0254d57d63a4.png)

как при добавлении объекта: 
![image](https://user-images.githubusercontent.com/70937147/134123784-43fba994-e0e5-4c05-adff-29770374e637.png)

**Comment by dzaybatsu** [comment]
#plan 30

**Comment by dzaybatsu** [comment]
#fact 60
