### ISSUE TITLE
При просмотре жалобы выводится ошибка

### ISSUE THREAD

**Issue by Aldikeeva** [qlt2020/doskaz#65]
Подала новую жалобу
![image](https://user-images.githubusercontent.com/70937147/134124498-3c4561ec-f4a9-4a61-9514-be38a7632269.png)

и вышла ошибка при просмотре: 
![image](https://user-images.githubusercontent.com/70937147/134124886-ce956a59-0dfd-4d37-8e04-634a53598f35.png)

при просмотре в админке тоже выводится ошибка: 
https://doskaz.kz/adminpanel/complaints

Ссылка на которую перенаправляет страница:
![image](https://user-images.githubusercontent.com/70937147/134125326-53bded6a-989a-4200-9639-5f0c760177ad.png)

**Comment by dosarkz** [comment]
поставил проверку при добавлении жалобы.
