### ISSUE TITLE
Залить переводы городов

### ISSUE THREAD

**Issue by Aldikeeva** [qlt2020/doskaz#66]
1. Отправьте, пожалуйста, документ для переводов 
2. Я подготовлю английскую версию
3. Задача: 

- [ ] Залить переводы

**Comment by dosarkz** [comment]
` ['id' => 106724, 'name' => 'Нур-Султан', 'nameKz' => 'Нұр-Сұлтан', 'bounds' => [[51.0006766, 71.2244414], [51.3511101, 71.7851913]]],
            ['id' => 158106, 'name' => 'Алматы', 'nameKz' => 'Алматы', 'bounds' => [[43.0328438, 76.7382775], [43.4036849, 77.1667539]]],
            ['id' => 110170, 'name' => 'Актау', 'nameKz' => 'Ақтау'],
            ['id' => 68402, 'name' => 'Актобе', 'nameKz' => 'Ақтөбе'],
            ['id' => 26551, 'name' => 'Атырау', 'nameKz' => 'Атырау'],
            ['id' => 80696, 'name' => 'Капшагай', 'nameKz' => 'Қапшағай'],
            ['id' => 212922, 'name' => 'Караганда', 'nameKz' => 'Қарағанды'],
            ['id' => 155241, 'name' => 'Кокшетау', 'nameKz' => 'Көкшетау'],
            ['id' => 125193, 'name' => 'Костанай', 'nameKz' => 'Қостанай'],
            ['id' => 165288, 'name' => 'Кызылорда', 'nameKz' => 'Қызылорда'],
            ['id' => 9103, 'name' => 'Павлодар', 'nameKz' => 'Павлодар', 'bounds' => [[52.2234455, 76.8608794], [52.3988251, 77.12136]]],
            ['id' => 33335, 'name' => 'Семей', 'nameKz' => 'Семей'],
            ['id' => 79497, 'name' => 'Талдыкорган', 'nameKz' => 'Талдықорған'],
            ['id' => 168533, 'name' => 'Тараз', 'nameKz' => 'Тараз'],
            ['id' => 182036, 'name' => 'Туркестан', 'nameKz' => 'Түркістан'],
            ['id' => 178771, 'name' => 'Шымкент', 'nameKz' => 'Шымкент'],
            ['id' => 51071, 'name' => 'Уральск', 'nameKz' => 'Орал'],
            ['id' => 31223, 'name' => 'Усть-Каменогорск', 'nameKz' => 'Өскемен'],
            ['id' => 113407, 'name' => 'Петропавловск', 'nameKz' => 'Петропавл'],
            ['id' => 1313, 'name' => 'Экибастуз', 'nameKz' => 'Екібастұз'],
            ['id' => 9, 'name' => 'Аксу', 'nameKz' => 'Ақсу'],
            ['id' => 211201, 'name' => 'Балхаш', 'nameKz' => 'Балқаш'],
            ['id' => 211888, 'name' => 'Жезказган', 'nameKz' => 'Жезқазған'],
            ['id' => 156843, 'name' => 'Степногорск', 'nameKz' => 'Степногорск'],
            ['id' => 125938, 'name' => 'Аркалык', 'nameKz' => 'Арқалық'],
            ['id' => 214204, 'name' => 'Сарань', 'nameKz' => 'Саран'],
            ['id' => 180937, 'name' => 'Арыс', 'nameKz' => 'Арыс'],
            ['id' => 181562, 'name' => 'Кентау', 'nameKz' => 'Кентау'],
            ['id' => 212498, 'name' => 'Каражал', 'nameKz' => 'Қаражал'],
            ['id' => 81062, 'name' => 'Текели', 'nameKz' => 'Текелі'],
            ['id' => 126778, 'name' => 'Рудный', 'nameKz' => 'Рудный'],
            ['id' => 168004, 'name' => 'Байконыр', 'nameKz' => 'Байқоңыр'],
            ['id' => 215326, 'name' => 'Шахтинск', 'nameKz' => 'Шахтинск'],
            ['id' => 214126, 'name' => 'Приозерск', 'nameKz' => 'Приозерск'],
            ['id' => 126589, 'name' => 'Лисаковск', 'nameKz' => 'Лисаковск'],
            ['id' => 214935, 'name' => 'Темиртау', 'nameKz' => 'Теміртау'],
            ['id' => 32845, 'name' => 'Риддер', 'nameKz' => 'Риддер'],
            ['id' => 110672, 'name' => 'Жанаозен', 'nameKz' => 'Жаңаөзен'],
            ['id' => 214573, 'name' => 'Сатпаев', 'nameKz' => 'Сәтбаев'],
            ['id' => 32808, 'name' => 'Курчатов', 'nameKz' => 'Курчатов'],`

**Comment by Aldikeeva** [comment]
@dosarkz 
['id' => 106724, 'name' => 'Нур-Султан', 'nameEn' => 'Nur-Sultan', 'bounds' => [[51.0006766, 71.2244414], [51.3511101, 71.7851913]]], ['id' => 158106, 'name' => 'Алматы', 'nameEn' => 'Almaty', 'bounds' => [[43.0328438, 76.7382775], [43.4036849, 77.1667539]]], ['id' => 110170, 'name' => 'Актау', 'nameEn' => '	Aktau'], ['id' => 68402, 'name' => 'Актобе', 'nameEn' => 'Aktobe'], ['id' => 26551, 'name' => 'Атырау', 'nameEn' => 'Atyrau'], ['id' => 80696, 'name' => 'Капшагай', 'nameEn' => 'Kapchagay'], ['id' => 212922, 'name' => 'Караганда', 'nameEn' => 'Karaganda'], ['id' => 155241, 'name' => 'Кокшетау', 'nameEn' => 'Kokshetau'], ['id' => 125193, 'name' => 'Костанай', 'nameEn' => 'Kostanay'], ['id' => 165288, 'name' => 'Кызылорда', 'nameEn' => '	Kyzylorda'], ['id' => 9103, 'name' => 'Павлодар', 'nameEn' => 'Pavlodar', 'bounds' => [[52.2234455, 76.8608794], [52.3988251, 77.12136]]], ['id' => 33335, 'name' => 'Семей', 'nameEn' => 'Semey'], ['id' => 79497, 'name' => 'Талдыкорган', 'nameEn' => 'Taldykorgan'], ['id' => 168533, 'name' => 'Тараз', 'nameEn' => 'Taraz'], ['id' => 182036, 'name' => 'Туркестан', 'nameEn' => 'Turkistan'], ['id' => 178771, 'name' => 'Шымкент', 'nameEn' => '	Shymkent'], ['id' => 51071, 'name' => 'Уральск', 'nameEn' => 'Oral'], ['id' => 31223, 'name' => 'Усть-Каменогорск', 'nameEn' => 'Oskemen'], ['id' => 113407, 'name' => 'Петропавловск', 'nameEn' => 'Petropavl'], ['id' => 1313, 'name' => 'Экибастуз', 'nameEn' => 'Ekibastuz'], ['id' => 9, 'name' => 'Аксу', 'nameEn' => 'Aksu'], ['id' => 211201, 'name' => 'Балхаш', 'nameEn' => 'Balkhash '], ['id' => 211888, 'name' => 'Жезказган', 'nameEn' => 'Jezkazgan'], ['id' => 156843, 'name' => 'Степногорск', 'nameEn' => 'Stepnogorsk'], ['id' => 125938, 'name' => 'Аркалык', 'nameEn' => 'Arkalyk'], ['id' => 214204, 'name' => 'Сарань', 'nameEn' => 'Saran'], ['id' => 180937, 'name' => 'Арыс', 'nameEn' => 'Arys'], ['id' => 181562, 'name' => 'Кентау', 'nameEn' => 'Kentau '], ['id' => 212498, 'name' => 'Каражал', 'nameEn' => 'Karazhal'], ['id' => 81062, 'name' => 'Текели', 'nameEn' => 'Tekeli'], ['id' => 126778, 'name' => 'Рудный', 'nameEn' => 'Rudny'], ['id' => 168004, 'name' => 'Байконыр', 'nameEn' => 'Baikonur'], ['id' => 215326, 'name' => 'Шахтинск', 'nameEn' => 'Shakhtinsk'], ['id' => 214126, 'name' => 'Приозерск', 'nameEn' => 'Priozersk'], ['id' => 126589, 'name' => 'Лисаковск', 'nameEn' => 'Lisakovsk'], ['id' => 214935, 'name' => 'Темиртау', 'nameEn' => 'Temirtau'], ['id' => 32845, 'name' => 'Риддер', 'nameEn' => 'Ridder'], ['id' => 110672, 'name' => 'Жанаозен', 'nameEn' => 'Zhanaozen'], ['id' => 214573, 'name' => 'Сатпаев', 'nameEn' => 'Satbayev'], ['id' => 32808, 'name' => 'Курчатов', 'nameEn' => 'Kurchatov'],

**Comment by dosarkz** [comment]
done
