### ISSUE TITLE
Подключить модерацию комментариев в админку

### ISSUE THREAD

**Issue by Aldikeeva** [qlt2020/doskaz#70]
приступить к задаче после завершения задачи на бэке - https://github.com/qlt2020/doskaz/issues/5

### Отзывы на объект 

- [x] После добавления отзыва - убрать автоматическую публикацию 
- [x] Добавить в админку раздел Отзывы 

Схема работы: 
1. Пользователь оставляет отзыв
2. В админке появляется запись в таблице
3. Администратор модерирует отзыв
4. У пользователя в ЛК отзыв выводится только после публикации 

**Поля в таблице:** 
Пользователь 
Текст отзыва 
Кнопки "Принять" и "Отклонить"
- По нажатию на кнопку "Принять" отзыв публикуется
- По нажатию на кнопку "Отклонить" отзыв не публикуется (если был опубликован становится не опубликованным - пропадет на сайте) 

________

### Комментарии в медиатеке

- [x] После добавления комментария - убрать автоматическую публикацию 
- [x] Добавить в админку раздел Комментарии

Схема работы: 
1. Пользователь оставляет комментарий 
2. В админке появляется запись в таблице
3. Администратор модерирует комментарий 
4. У пользователя в ЛК комментарий выводится только после публикации 

**Поля в таблице:** 
Пользователь 
Текст комментария
Кнопки "Принять" и "Отклонить"
- По нажатию на кнопку "Принять" комментарий публикуется
- По нажатию на кнопку "Отклонить" комментарий не публикуется (если был опубликован становится не опубликованным - пропадет на сайте)

**Comment by Rokatoka** [comment]
#plan 150
