### ISSUE TITLE
При добавлении объекта автоматическая оценка указана как Недоступно

### ISSUE THREAD

**Issue by Aldikeeva** [qlt2020/doskaz#77]
Параметр Зона оказания услуги - форма для Волонтеров 
https://doskaz.kz/objects/add#95
![image](https://user-images.githubusercontent.com/70937147/134159441-61122707-bdb0-4a72-a128-b88b8eae0ea6.png)

Первоначально у всех объектов указан вариант "Не известно" и оценка доступности должна быть пустая: 
![image](https://user-images.githubusercontent.com/70937147/134159571-3c558ced-0c12-4f6f-bafa-29c5c697a3dc.png)

**Comment by Rokatoka** [comment]
бэк закроет
