### ISSUE TITLE
Общая статистика (графики)

### ISSUE THREAD

**Issue by Aldikeeva** [qlt2020/doskaz#8]
- [x] Переместить статистику по объектам и пользователям выше, а по жалобам и обращениям ниже:
![image](https://user-images.githubusercontent.com/70937147/133967690-30d23403-e86a-4461-aa78-18daca93fae3.png)

- [x] Настроить категории по возрасту и  добавить вариант "Все группы"
![image](https://user-images.githubusercontent.com/70937147/133967734-ee872bef-bdfd-48c9-bf7c-00a2a59fa297.png)

- [x] Дописать в табы "... по всем категориям"
- [x] Выводить в диаграмме все объекты по доступности:
![image](https://user-images.githubusercontent.com/70937147/133967898-b856543e-7ded-4be1-9fdb-776d783b86de.png)

- [x] вывести цифры (кол-во объектов) - если получится 

- [x] Добавить в наименования месяца 
![image](https://user-images.githubusercontent.com/70937147/133972501-5949ec5e-2058-4612-b96f-655be20558ff.png)

**Comment by Kainar9292** [comment]
#plan 300

**Comment by Kainar9292** [comment]
#plan 320
